plugin: community.proxmox.proxmox
url: "{{ lookup('env', 'TF_VAR_proxmox_api_url_vip') }}"
user: "{{ lookup('env', 'TF_VAR_proxmox_api_user') }}"
token_id: "{{ lookup('env', 'TF_VAR_proxmox_api_token_id') }}"
token_secret: "{{ lookup('env', 'TF_VAR_proxmox_api_token_secret') }}"
validate_certs: false
timeout: 60
qemu_agent: true
want_facts: true
want_lxc: false
want_vm: true
strict: false

compose:
  ansible_host: "proxmox_ipconfig0.ip | default('') | regex_replace('/.*', '')"
  _vm_os:   "inventory_hostname.split('-')[0] | upper"
  _vm_role: "inventory_hostname.split('-')[1] | upper"

keyed_groups:
  - prefix: OS
    key: _vm_os
  - prefix: ROLE
    key: _vm_role