---
- name: "Deployment Core Infra : Syslog"
  hosts: ROLE_RSYS
  remote_user: cloudadm
  become: true
  vars:
    rsyslog_log_dir: "/var/log/fortigate"
    rsyslog_port: 514
  roles:
    - common
    - syslog