name: "00. SecOps & Quality"
permissions:
  contents: read

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  # --- SCAN SECRETS ---
  gitleaks:
    name: Gitleaks Scan
    runs-on: [self-hosted, nuuk-runner]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - name: Gitleaks Check
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # --- ANALYSE DE SÉCURITÉ IAC ---
  trivy-iac:
    name: Trivy IaC Scan
    runs-on: [self-hosted, nuuk-runner]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@97e0b3872f55f89b95b2f65b3dbab56962816478 # v0.34.2
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1' # Echoue si une faille est trouvée
          severity: 'CRITICAL,HIGH'

  # --- QUALITÉ TERRAFORM & ANSIBLE ---
  lint-and-validate:
    name: Lints & Validation
    runs-on: [self-hosted, nuuk-runner]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate (Global modules)
        run: |
          for dir in terraform/composants/*; do
            if [ -d "$dir" ]; then
              echo "Validating $dir..."
              terraform -chdir=$dir init -backend=false
              terraform -chdir=$dir validate
            fi
          done

      - name: Install and Run Ansible-lint
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install ansible-lint
          # On ne lance le linter que si des fichiers .yml/.yaml existent
          if [ -d "ansible/playbooks" ]; then
            PLAYBOOKS=$(find ansible/playbooks -maxdepth 1 -name "*.yml" -o -name "*.yaml" 2>/dev/null)
            if [ -n "$PLAYBOOKS" ]; then
              export ANSIBLE_ROLES_PATH=./ansible/roles
              ansible-lint $PLAYBOOKS
            else
              echo "Aucun playbook trouvé, skip lint."
            fi
          else
            echo "Répertoire ansible/playbooks non trouvé, skip lint."
          fi