name: "01. Socle - Infrastructure"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement (poc ou nuuk)"
        required: true
        type: choice
        options: [poc, nuuk]
        default: nuuk

      # --- CONTRÔLE TERRAFORM ---
      run_terraform:
        description: "Exécuter Terraform ?"
        type: boolean
        default: true
      terraform_action:
        description: "Action Terraform (apply/plan/destroy)"
        type: choice
        options: [apply, plan, destroy]
        default: apply
      target_scope_tf:
        description: "Composants à traiter"
        type: choice
        options: [Tous, Sélection]
        default: Sélection

      # --- SÉLECTION MANUELLE
      deploy_tf_bastion:
        description: "Bastion"
        type: boolean
        default: false
      deploy_tf_dhcp:
        description: "DHCP (Node1 + Node2)"
        type: boolean
        default: false
      deploy_tf_addns:
        description: "ADDNS"
        type: boolean
        default: false
      deploy_tf_rsys:
        description: "RSYSLOG"
        type: boolean
        default: false
      
      # --- CONTRÔLE ANSIBLE ---
      run_ansible:
        description: "Exécuter Ansible ?"
        type: boolean
        default: true
      target_scope_ans:
        description: "Composants à traiter"
        type: choice
        options: [Tous, Sélection]
        default: Sélection

      # --- SÉLECTION MANUELLE ---
      deploy_ans_bastion:
        description: "Cible : Bastion"
        type: boolean
        default: false
      deploy_ans_dhcp:
        description: "Cible : DHCP"
        type: boolean
        default: false

jobs:
  deploy:
    name: "Provisionnement & Configuration"
    runs-on: [self-hosted, "${{ github.event.inputs.environment }}-runner"]
    environment: ${{ github.event.inputs.environment }}

    env:
      # --- SECRETS ---
      TF_CLOUD_ORGANIZATION: "nuuk"

      # PROXMOX
      TF_VAR_proxmox_api_url_node_1: ${{ secrets.PVE_API_URL_NODE_1 }}
      TF_VAR_proxmox_api_url_node_2: ${{ secrets.PVE_API_URL_NODE_2 }}
      TF_VAR_proxmox_api_url_node_3: ${{ secrets.PVE_API_URL_NODE_3 }}
      TF_VAR_proxmox_api_url_vip: ${{ secrets.PVE_API_URL_VIP }}
      TF_VAR_proxmox_api_user: ${{ secrets.PVE_API_USER }}
      TF_VAR_proxmox_api_token_id: ${{ secrets.PVE_TOKEN_ID }}
      TF_VAR_proxmox_api_token_secret: ${{ secrets.PVE_TOKEN_SECRET }}
      TF_VAR_datastore_id: ${{ vars.TF_DATASTORE_ID }}
      
      # NETWORK
      TF_VAR_ip_bastion_01: ${{ vars.TF_IP_BASTION_01 }}
      TF_VAR_ip_bastion_02: ${{ vars.TF_IP_BASTION_02 }}
      TF_VAR_bastion_vip: ${{ vars.TF_IP_BASTION_VIP }}
      TF_VAR_ip_dhcp_02: ${{ vars.TF_IP_DHCP_02 }}
      TF_VAR_ip_dhcp_01: ${{ vars.TF_IP_DHCP_01 }}
      TF_VAR_ip_addns_01: ${{ vars.TF_IP_ADDNS_01 }}
      TF_VAR_ip_addns_02: ${{ vars.TF_IP_ADDNS_02 }}
      TF_VAR_ip_rsys_01: ${{ vars.TF_IP_RSYS_01 }}
      TF_VAR_gateway_vlan70: ${{ vars.TF_GATEWAY_VLAN70 }}
      TF_VAR_gateway_vlan40: ${{ vars.TF_GATEWAY_VLAN40 }}
      TF_VAR_gateway_vlan50: ${{ vars.TF_GATEWAY_VLAN50 }}
      TF_VAR_ip_node_1: ${{ vars.TF_IP_NODE_1 }}
      TF_VAR_ip_node_2: ${{ vars.TF_IP_NODE_2 }}
      TF_VAR_ip_node_3: ${{ vars.TF_IP_NODE_3 }}
      TF_VAR_network_v1: ${{ vars.TF_NETWORK_V1 }}
      TF_VAR_network_v2: ${{ vars.TF_NETWORK_V2 }}

      BASTION_PASS: ${{ secrets.BASTION_PASS }}

      
      ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      ANSIBLE_CONFIG: "${{ github.workspace }}/ansible/ansible.cfg"
      # --- TF_VARS ---
      TF_VAR_environnement: ${{ github.event.inputs.environment }}
      BASTION_IFACE: ${{ vars.BASTION_IFACE }}
      BASTION_ROUTER_ID: ${{ vars.BASTION_ROUTER_ID }}
      TF_VAR_ssh_public_keys: "${{ vars.SSH_PUBLIC_KEYS }}"

      TF_VAR_node_name_linux_1: ${{ vars.TF_NAME_NODE_UNIX_1 }}
      TF_VAR_node_name_linux_2: ${{ vars.TF_NAME_NODE_UNIX_2 }}
      TF_VAR_node_name_linux_3: ${{ vars.TF_NAME_NODE_UNIX_3 }}
      TF_VAR_node_name_win_gui_1: ${{ vars.TF_NAME_NODE_WIN_1 }}
      TF_VAR_node_name_win_core_2: ${{ vars.TF_NAME_NODE_WIN_2 }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: SSH Agent Setup
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Terraform
        if: github.event.inputs.run_terraform == 'true'
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      
      - name: Install Ansible collections
        if: github.event.inputs.run_ansible == 'true'
        run: |
          ansible-galaxy collection install -r ansible/requirements.yml

      # ==========================================
      # BLOC 01 : BASTION
      # ==========================================
      - name: "[TF] Bastion"
        if: |
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_bastion == 'true' ||
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
        id: tf_bastion
        continue-on-error: false
        run: |
          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-01-bastion"
          terraform -chdir=terraform/composants/01_bastion init
          terraform -chdir=terraform/composants/01_bastion ${{ github.event.inputs.terraform_action }} -auto-approve -parallelism=1

      - name: "[CLEAN] Proxmox Bastion (si fail)"
        if: failure() && steps.tf_bastion.outcome == 'failure'
        run: |
          for VMID in 401 402; do
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
          done
      
      - name: "[HEALTHCHECK] Bastion"
        id: healthcheck_bastion
        if: |
          success() &&
          github.event.inputs.run_ansible == 'true' && (
            github.event.inputs.target_scope_ans == 'Tous' ||
            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_bastion == 'true')
          )
        run: |
          IP1="${{ vars.TF_IP_BASTION_01 }}"
          IP2="${{ vars.TF_IP_BASTION_02 }}"

          echo "Attente du réseau sur $IP1 et $IP2..."
          for IP in $IP1 $IP2; do
            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
            echo "$IP est prêt pour SSH"
          done

      - name: "[ANS] Config Bastion"
        if: |
          success() &&
          steps.healthcheck_bastion.outcome == 'success'
        run: |
          cd ansible
          ansible-playbook -i inventory/inventory.proxmox.yml 01_deploy_bastions.yml

      # ==========================================
      # BLOC 02 : DHCP
      # ==========================================
      - name: "[TF] DHCP (Node1 + Node2)"
        if: |
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_dhcp == 'true' ||
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
        id: tf_dhcp
        run: |
          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
          terraform -chdir=terraform/composants/02_core_infra init
          terraform -chdir=terraform/composants/02_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -parallelism=1 \
            -target='module.dhcp_node1' \
            -target='module.dhcp_node2'

      - name: "[CLEAN] Proxmox DHCP (si fail)"
        if: failure() && steps.tf_dhcp.outcome == 'failure'
        run: |
          for VMID in 701 702; do
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
          done

      - name: "[HEALTHCHECK] DHCP"
        id: healthcheck_dhcp
        if: |
          success() &&
          github.event.inputs.run_ansible == 'true' && (
            github.event.inputs.target_scope_ans == 'Tous' ||
            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_dhcp == 'true')
          )
        run: |
          IP1="${{ vars.TF_IP_DHCP_01 }}"
          IP2="${{ vars.TF_IP_DHCP_02 }}"

          echo "Attente du réseau sur $IP1 et $IP2..."
          for IP in $IP1 $IP2; do
            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
            echo "$IP est prêt pour SSH"
          done

      - name: "[ANS] Config DHCP"
        if: |
          success() &&
          steps.healthcheck_dhcp.outcome == 'success'
        run: |
          cd ansible
          ansible-playbook -i inventory/inventory.proxmox.yml 02_deploy_dhcp.yml

      # ==========================================
      # BLOC 03 : ADDNS
      # ==========================================
      - name: "[TF] ADDNS"
        if: |
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_addns == 'true' ||
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
        id: tf_addns
        run: |
          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
          terraform -chdir=terraform/composants/02_core_infra init
          terraform -chdir=terraform/composants/02_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -target='module.addns_node1' -target='module.addns_node2' -parallelism=1

      - name: "[CLEAN] Proxmox ADDNS (si fail)"
        if: failure() && steps.tf_addns.outcome == 'failure'
        run: |
          for VMID in 711; do
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_1 }} "qm unlock $VMID || true"
          done
          for VMID in 712; do
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_2 }} "qm unlock $VMID || true"
          done

      - name: "[HEALTHCHECK] ADDNS"
        id: healthcheck_addns
        if: |
          success() && github.event.inputs.run_ansible == 'true' && (
            github.event.inputs.target_scope_ans == 'Tous' ||
            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_addns == 'true')
          )
        run: |
          IP1="${{ vars.TF_IP_ADDNS_01 }}"
          IP2="${{ vars.TF_IP_ADDNS_02 }}"

          echo "Attente du réseau sur $IP1 et $IP2..."
          for IP in $IP1 $IP2; do
            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
            echo "$IP est prêt pour SSH"
          done

      # ==========================================
      # BLOC 04 : RSYSLOG
      # ==========================================
      - name: "[TF] RSYSLOG"
        if: |
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Sélection' && github.event.inputs.deploy_tf_rsys == 'true' ||
          github.event.inputs.run_terraform == 'true' && github.event.inputs.target_scope_tf == 'Tous'
        id: tf_rsys
        run: |
          export TF_WORKSPACE="nuuk-medilab-${{ github.event.inputs.environment }}-02-core-infra"
          terraform -chdir=terraform/composants/02_core_infra init
          terraform -chdir=terraform/composants/02_core_infra ${{ github.event.inputs.terraform_action }} -auto-approve -target='module.rsys_node3' -parallelism=1

      - name: "[CLEAN] Proxmox RSYSLOG (si fail)"
        if: failure() && steps.tf_rsys.outcome == 'failure'
        run: |
          for VMID in 501; do
            ssh -o StrictHostKeyChecking=no root@${{ vars.TF_IP_NODE_3 }} "qm unlock $VMID || true"
          done

      - name: "[HEALTHCHECK] RSYSLOG"
        id: healthcheck_rsys
        if: |
          success() && github.event.inputs.run_ansible == 'true' && (
            github.event.inputs.target_scope_ans == 'Tous' ||
            (github.event.inputs.target_scope_ans == 'Sélection' && github.event.inputs.deploy_ans_rsys == 'true')
          )
        run: |
          IP1="${{ vars.TF_IP_RSYS_01 }}"

          echo "Attente du réseau sur $IP1..."
          for IP in $IP1; do
            timeout 180s bash -c "until ping -c 1 -W 1 $IP > /dev/null; do echo 'Waiting for $IP...'; sleep 5; done"
            timeout 120s bash -c "until nc -zvw1 $IP 22; do sleep 5; done"
            echo "$IP est prêt pour SSH"
          done